# Generated by Django 6.0.7 on 2026-08-20 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_finance', '0013_alter_affectationtransport_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('capacite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('maintenance', 'Maintenance'), ('hors_service', 'Hors Service')], default='actif', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('depart', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AffectationTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=False)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_finance.personnel')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='logistique.bus')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.trajet')),
            ],
            options={
                'ordering': ['-date_debut'],
                'unique_together': {('bus', 'trajet', 'date_debut')},
            },
        ),
    ]
