# Generated by Django 6.0.2 on 2026-04-13 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_payement', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=20, null=True)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en attente', 'En attente'), ('partiel', 'Partiel')], default='en_attente', max_length=15)),
                ('date_payement', models.DateField(blank=True, null=True)),
                ('mois_concerne', models.CharField(blank=True, help_text='Format : 2026-04', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('poste', models.CharField(choices=[('administratif', 'Administratif'), ('technique', 'Technique'), ('securite', 'Securite'), ('entretien', 'Entretien'), ('autre', 'Autre')], default='administratif', max_length=20)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_paiement', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=20, null=True)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en attente', 'En attente'), ('partiel', 'Partiel')], default='en_attente', max_length=15)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('mois_concerne', models.CharField(blank=True, help_text='Format : 2025-04', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
