# Generated by Django 6.0.2 on 2026-04-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0003_enseignant_personnel_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('vacataire', 'Vacataire')], default='permanent', max_length=20),
        ),
    ]
