# Generated by Django 6.0.2 on 2026-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0004_enseignant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='date_payement',
            new_name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='mode_payement',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=20, null=True),
        ),
    ]
