# Generated by Django 6.0.2 on 2026-04-25 22:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0005_rename_date_payement_enseignant_date_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
