# Generated by Django 6.0.1 on 2026-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0006_payment_student_date_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personnel',
            name='matricule',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
