# Generated by Django 6.0.1 on 2026-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0007_enseignant_matricule_personnel_matricule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_echeance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='statut',
            field=models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('en_attente', 'En attente')], default='en_attente', max_length=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('administratif', 'Administratif'), ('technique', 'Technique'), ('securite', 'Sécurité'), ('entretien', 'Entretien'), ('autre', 'Autre')], default='administratif', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='statut',
            field=models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('en_attente', 'En attente')], default='en_attente', max_length=15),
        ),
    ]
