# Generated by Django 6.0.1 on 2026-05-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0009_bus_affectationtransport_trajet_depensetransport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depensetransport',
            options={'ordering': ['-date']},
        ),
    ]
