# Generated by Django 5.1.15 on 2026-07-11 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0003_alter_anneeacademique_options_and_more'),
        ('gestion_finance', '0011_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_paiement', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=20, null=True)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('non_paye', 'Non payé')], default='non_paye', max_length=10)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_financier', to='gestion_eleves.etudiant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
