# Generated by Django 6.0.7 on 2026-08-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0012_dossierfinancier_delete_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectationtransport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='affectationtransport',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='affectationtransport',
            name='chauffeur',
        ),
        migrations.RemoveField(
            model_name='affectationtransport',
            name='trajet',
        ),
    ]
