# Generated by Django 6.0.7 on 2026-08-20 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finance', '0013_alter_affectationtransport_unique_together_and_more'),
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depensetransport',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='logistique.bus'),
        ),
        migrations.DeleteModel(
            name='AffectationTransport',
        ),
        migrations.DeleteModel(
            name='Trajet',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
