# Generated by Django 5.1.15 on 2026-07-23 08:09

import django.core.validators
import django.db.models.deletion
import gestion_eleves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0002_add_statut_etudiant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneeacademique',
            options={'ordering': ['-nom'], 'verbose_name': 'Année Académique', 'verbose_name_plural': 'Années Académiques'},
        ),
        migrations.AlterModelOptions(
            name='compteetudiant',
            options={'verbose_name': 'Compte Étudiant', 'verbose_name_plural': 'Comptes Étudiants'},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
        migrations.AlterModelOptions(
            name='faculte',
            options={'ordering': ['nom'], 'verbose_name': 'Faculté', 'verbose_name_plural': 'Facultés'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['portail', 'nom'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['ue', 'nom'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['etudiant', 'semestre', 'matiere'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='parametresuccb',
            options={'verbose_name': 'Paramètres Généraux UCCB', 'verbose_name_plural': 'Paramètres Généraux UCCB'},
        ),
        migrations.AlterModelOptions(
            name='portail',
            options={'ordering': ['faculte', 'nom'], 'verbose_name': 'Portail (Tronc Commun)', 'verbose_name_plural': 'Portails (Troncs Communs)'},
        ),
        migrations.AlterModelOptions(
            name='resultatsemestre',
            options={'ordering': ['etudiant', 'semestre'], 'verbose_name': 'Résultat de Semestre', 'verbose_name_plural': 'Résultats de Semestre'},
        ),
        migrations.AlterModelOptions(
            name='uniteenseignement',
            options={'ordering': ['semestre', 'code_ue'], 'verbose_name': "Unité d'Enseignement (UE)", 'verbose_name_plural': "Unités d'Enseignement (UE)"},
        ),
        migrations.AlterField(
            model_name='anneeacademique',
            name='nom',
            field=models.CharField(help_text='Format obligatoire : 2025-2026', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}$', 'Format : AAAA-AAAA')]),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='actif',
            field=models.BooleanField(default=True, help_text="Désactiver pour bloquer l'accès sans supprimer le compte.", verbose_name='Compte actif'),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='etudiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_etudiant', to='gestion_eleves.etudiant', verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='mot_de_passe',
            field=models.CharField(max_length=128, verbose_name='Mot de passe (hashé)'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(validators=[gestion_eleves.models.valider_date_naissance]),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='en_regle',
            field=models.BooleanField(default=True, help_text="Décocher si l'étudiant a des impayés. Géré par le secrétariat ou le module finance.", verbose_name='En règle financièrement'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(blank=True, help_text='S3 et au-delà uniquement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_eleves.filiere'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s\\-]+$', 'Lettres, espaces et tirets uniquement.')]),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='portail',
            field=models.ForeignKey(blank=True, help_text='S1 et S2 uniquement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_eleves.portail'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s\\-]+$', 'Lettres, espaces et tirets uniquement.')]),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], default='S1', max_length=3),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif — étudiant en cours'), ('diplome', 'Diplômé — a terminé son cycle'), ('abandonne', 'Abandonné — a quitté sans terminer')], default='actif', help_text="Actif = visible dans les classes. Diplômé/Abandonné = conserve son compte et ses relevés mais n'apparaît plus dans les promotions.", max_length=20, verbose_name="Statut de l'étudiant"),
        ),
        migrations.AlterField(
            model_name='faculte',
            name='code',
            field=models.CharField(help_text='Ex: FST', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='code',
            field=models.CharField(help_text='Ex: INFO, BIO, PHYS', max_length=10),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='portail',
            field=models.ForeignKey(help_text='Portail parent de cette filière', on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='gestion_eleves.portail'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='credits',
            field=models.IntegerField(default=2, help_text='Entre 1 et 10 crédits', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_devoir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_session',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_sr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Rattrapage (SR)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], max_length=3),
        ),
        migrations.AlterField(
            model_name='parametresuccb',
            name='nom_secretaire',
            field=models.CharField(max_length=200, verbose_name='Nom du Secrétaire Universitaire'),
        ),
        migrations.AlterField(
            model_name='portail',
            name='code',
            field=models.CharField(help_text='Ex: MIP, BCG, PCG', max_length=10),
        ),
        migrations.AlterField(
            model_name='resultatsemestre',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], max_length=3),
        ),
        migrations.AlterField(
            model_name='uniteenseignement',
            name='filiere',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour S3+', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='gestion_eleves.filiere'),
        ),
        migrations.AlterField(
            model_name='uniteenseignement',
            name='portail',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour S1-S2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='gestion_eleves.portail'),
        ),
        migrations.AlterField(
            model_name='uniteenseignement',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('portail', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere', 'semestre')},
        ),
        migrations.AlterUniqueTogether(
            name='portail',
            unique_together={('faculte', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='resultatsemestre',
            unique_together={('etudiant', 'semestre', 'annee')},
        ),
        migrations.CreateModel(
            name='EtudiantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to='gestion_eleves.etudiant')),
            ],
            options={
                'verbose_name': 'Compte Étudiant',
                'verbose_name_plural': 'Comptes Étudiants',
            },
        ),
    ]
