# Generated by Django 5.1.15 on 2026-08-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0004_filiere_faculte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['faculte', 'nom'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('faculte', 'code')},
        ),
        migrations.AlterField(
            model_name='filiere',
            name='faculte',
            field=models.ForeignKey(blank=True, help_text='Faculté de cette filière', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='gestion_eleves.faculte'),
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='portail',
        ),
    ]
