# Generated by Django 5.1.15 on 2026-08-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0005_alter_filiere_options_alter_filiere_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif — étudiant en cours'), ('diplome', 'Diplômé — a terminé son cycle'), ('abandonne', 'Abandonné — a quitté sans terminer')], default='actif', help_text='Actif = visible dans les classes. Diplômé/Abandonné = conserve son compte et ses relevés.', max_length=20, verbose_name="Statut de l'étudiant"),
        ),
        migrations.DeleteModel(
            name='EtudiantUser',
        ),
    ]
