# Generated by Django 5.1.15 on 2026-08-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0006_alter_etudiant_statut_delete_etudiantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='portails',
            field=models.ManyToManyField(blank=True, help_text='Portails (S1-S2) donnant accès à cette filière', related_name='filieres', to='gestion_eleves.portail'),
        ),
    ]
