# Generated by Django 5.1.15 on 2026-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0007_filiere_portails'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
