# Generated by Django 5.1.15 on 2026-08-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0008_etudiant_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniteenseignement',
            name='code_ue',
            field=models.CharField(max_length=20),
        ),
    ]
