# Generated by Django 5.1.15 on 2026-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0009_alter_uniteenseignement_code_ue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniteenseignement',
            name='code_ue',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
