# Generated by Django 5.1.15 on 2026-08-23 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eleves', '0010_alter_uniteenseignement_code_ue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s\\-]+$', 'Lettres, espaces et tirets uniquement.')])),
                ('prenom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s\\-]+$', 'Lettres, espaces et tirets uniquement.')])),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('nationalite', models.CharField(blank=True, default='Congolaise', max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('rib', models.CharField(blank=True, help_text="Pour le versement du salaire / des vacations par l'Espace Finance", max_length=50, null=True, verbose_name='RIB (coordonnées bancaires)')),
                ('numero_secu', models.CharField(blank=True, max_length=40, null=True, verbose_name='Numéro de sécurité sociale / CNSS')),
                ('diplome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diplôme le plus élevé')),
                ('chef_departement', models.BooleanField(default=False, verbose_name='Chef de filière / département')),
                ('statut', models.CharField(choices=[('vacataire', 'Vacataire'), ('permanent', 'Permanent')], default='vacataire', max_length=12)),
                ('date_debut_contrat', models.DateField(blank=True, null=True)),
                ('date_fin_contrat', models.DateField(blank=True, help_text='Laisser vide pour un permanent (CDI). Obligatoire pour un vacataire.', null=True)),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, help_text='Montant par heure de cours (vacataire uniquement)', max_digits=10, null=True)),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire mensuel fixe (permanent uniquement)', max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True, help_text="Intervient activement au sein de l'année académique en cours")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(help_text='Année académique de référence de cet enseignant', on_delete=django.db.models.deletion.PROTECT, related_name='enseignants', to='gestion_eleves.anneeacademique')),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enseignants', to='gestion_eleves.faculte')),
                ('filiere', models.ForeignKey(blank=True, help_text='Département de rattachement (une filière = un département)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='gestion_eleves.filiere')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='AffectationVacataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], max_length=3)),
                ('volume_horaire_prevu', models.DecimalField(decimal_places=1, help_text="Nombre d'heures prévues (fiche d'engagement) pour ce semestre", max_digits=6)),
                ('volume_confirme_faculte', models.BooleanField(default=False, help_text='Coché par la Faculté une fois les heures effectivement réalisées — sert de feu vert pour la Finance')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_vacataires', to='gestion_eleves.faculte')),
                ('filiere', models.ForeignKey(blank=True, help_text="Laisser vide si l'intervention concerne toute la faculté (ex: cours transversal)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_vacataires', to='gestion_eleves.filiere')),
                ('portail', models.ForeignKey(blank=True, help_text='Tronc commun S1-S2 (laisser vide si filière ou toute la faculté)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_vacataires', to='gestion_eleves.portail')),
                ('enseignant', models.ForeignKey(limit_choices_to={'statut': 'vacataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='gestion_eleves.enseignant')),
            ],
            options={
                'verbose_name': 'Affectation Vacataire',
                'verbose_name_plural': 'Affectations Vacataires',
                'ordering': ['semestre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueVolumeHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_volume', models.DecimalField(decimal_places=1, max_digits=6)),
                ('nouveau_volume', models.DecimalField(decimal_places=1, max_digits=6)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='gestion_eleves.affectationvacataire')),
            ],
            options={
                'verbose_name': 'Historique Volume Horaire',
                'verbose_name_plural': 'Historiques Volume Horaire',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s\\-]+$', 'Lettres, espaces et tirets uniquement.')])),
                ('prenom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s\\-]+$', 'Lettres, espaces et tirets uniquement.')])),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fonction', models.CharField(choices=[('menage', 'Agent de ménage'), ('gardien', 'Gardien / Agent de sécurité'), ('cuisinier', 'Cuisinier'), ('chauffeur', 'Chauffeur'), ('technicien', 'Technicien de maintenance'), ('autre', 'Autre')], max_length=20)),
                ('fonction_autre', models.CharField(blank=True, help_text="Précision si 'Autre' est sélectionné", max_length=100, null=True)),
                ('lieu_travail', models.CharField(help_text='Ex: Faculté des Sciences, Résidence universitaire, Administration centrale...', max_length=150)),
                ('date_embauche', models.DateField()),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, help_text="Salaire mensuel — transmis à l'Espace Finance pour la paie", max_digits=10, null=True)),
                ('rib', models.CharField(blank=True, help_text="Pour le versement du salaire par l'Espace Finance", max_length=50, null=True, verbose_name='RIB (coordonnées bancaires)')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('faculte_rattachement', models.ForeignKey(blank=True, help_text='Si rattaché à une faculté en particulier (facultatif)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='gestion_eleves.faculte')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='InterventionEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], max_length=3)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_eleves.anneeacademique')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion_eleves.enseignant')),
            ],
            options={
                'verbose_name': 'Intervention Enseignant',
                'verbose_name_plural': 'Interventions Enseignants',
                'ordering': ['semestre'],
                'unique_together': {('enseignant', 'annee_academique', 'semestre')},
            },
        ),
    ]
